### ISSUE TITLE
I have textures for blocks/sprites enabled, yet the textures do not seem to appear (Fixed)

### ISSUE THREAD

**Issue by JDSammy** [TEdit/Terraria-Map-Editor#1050]
In more detail, the blocks stay in the main block color that they are, like from a distance, but if you zoom in, it seems to stay like that. The sprite menu's items are invisible, and on the map all sprites already placed are a neon pink.

## What were you doing when the issue occured?
I was about to edit a tedious building process.
## Can you reproduce the issue?
Everytime a load a world on TEdit this occurs. I have reinstalled it and the effects are the same.
## What version of Terraria are you using?
1.3.5.
## Post relevant contents of log or attach log file _**(very important)**_:
The program did not crash, therefore I dont believe this is needed, request if I need to attach one.

**Comment by JDSammy** [comment]
I have fixed this by moving the install folder of terraria from E: (hard drive) to C: (local disk) and the textures reappeared.

**Comment by MitchDifre** [comment]
Hello guys, im having the same problem as your. The application seems to process due i can change tiles and blocks, but the problem is the same as this post... my texture won't load and keep having the pixelated texture. I have the installation folder on C: (local disk) but the problem won't solve. Please if you know any solution i'll be grateful to you.

**Comment by georgeRussian** [comment]
Help solve the problem, I have instead of playing textures the colors of these textures, i.e. if the block of earth in terraria is brown , but with the addition of other elements , then in tedit just the whole block is brown. If this folder is changed, the Microsoft framework is installed and the latest

**Comment by JocaBr1** [comment]
@georgeRussian I do not understand anything you said, I have the same problem and n know how to solve could simplify?

**Comment by Roadhouse666** [comment]
I'm very confused why the textures are not loading when I zoom in but can't find a solution. What do I need to do to fix the problem.

**Comment by 6utterflu** [comment]
I have been struggling with this for 7 hours already I have been using both Russian and English sites and ... help T.T

**Comment by BinaryConstruct** [comment]
https://github.com/TEdit/Terraria-Map-Editor/wiki/Install-Requirements#for-sprite-viewing
