### ISSUE TITLE
Saved new world in Tedit, loaded fine a couple of times, won't load now.

### ISSUE THREAD

**Issue by SpartanG01** [TEdit/Terraria-Map-Editor#1081]
[World and Log File](https://github.com/TEdit/Terraria-Map-Editor/files/2001871/New.WinRAR.ZIP.archive.zip)

## What were you doing when the issue occured?
I made a few basic edits to a world (Hellavator + built an NPC hotel, literally nothing else)

## Can you reproduce the issue?
Yeah

## What version of Terraria are you using?
1.3.5 (whatever the most recent on Steam is)

**Comment by SpartanG01** [comment]
#750 is a version issue. I'm using 3.10 for Terraria 1.3.5 so I don't think that's the issue, also it did work. It just stopped randomly.

#493 is closed with a reference to #1073 which again is a bad version issue with a new release of Tedit that was fixed already.

#558 version issue regarding someone using much older version of terraria. Not related.

#427 Out of Date Terraria. Not my issue.

#228 Out of Date Tedit. Not my issue.

**Comment by BinaryConstruct** [comment]
Sometimes this happens if there is an issue saving the file, or it gets restored from backup by Terraria automatically. Probably the only option is to keep a backup of a known working file, make edits to a new file, test, and if it works, replace the backup.  Not the most intuitive workflow, but it will give an extra margin of safety for your world files and your edits. Personally I use a local git repo for my world files and edits. It isn't the most storage friendly method, but it ensures backups.
