### ISSUE TITLE
Real tile graphics on close-up view

### ISSUE THREAD

**Issue by SineSwiper** [TEdit/Terraria-Map-Editor#130]
You should really consider actually using the game image data for the maps. Do you know how hard it would be to try to actually construct a tree when all you have is a brown color and frame coordinates?? I was using <A href="http://www.terrariaonline.com/threads/xnb-exporter-extract-graphics-from-terraria.16058/">this XNB Exporter</a> to look at the individual images and frames. You should code the editor to (perhaps at a certain zoom level) use the real frames to render the map, using either the XNB game data directly, or put the PNG data into the editor.

Looks like this may be a revival of issue #20, but that was eons ago, and with the new Frame tag data/research, this should be achievable:
1. Load all PNG files into memory.
2. Run through each tile within view (plus some excess).
3. For each Tile numbered X, look at Tile_X.png in-memory image.
4. If not isFramed, use the whole image.
5. If isFramed, look at Frame X,Y.  Divide by 2.  Go to X,Y on image.  Assume 8x8 pixel tile.
6. Plop tile/image on map location.

**Comment by DumbJoe** [comment]
...so the feature is in it the latest beta? Because I still can't see ingame texture sprites.....would be nice if there was an option to specify the location of the images directory just like how Terrafirma ask for it if you wish to see ingame textures of the world...if you want to use the editor on another computer that doesn't have Terraria installed, for example you have Terraria installed on a windows xp machine but have a spare windows 7 machine lying around you could use but barely use because it's extremely slow(for example which might be why you don't wanna run the game on that), since the program doesnt run on windows xp machine, you could load the editor, copy the images directory and sub contents with the editor and the tell the editor where the images are at so it can use the ingame textures....
