### ISSUE TITLE
Can't Load Worlds

### ISSUE THREAD

**Issue by Ladeio** [TEdit/Terraria-Map-Editor#1387]
When I try to load a fresh world it always doesn't load and shows this:

![Screenshot](https://user-images.githubusercontent.com/69992750/90831088-a21bba80-e34b-11ea-9c94-b8eec5f2f88e.png)

I'm guessing it's because the computer memory can't handle it, but when I check it it doesn't even get too high.

Windows 7
Tedit 4 beta 31
Terraria Version1.4.0.4

**Comment by BinaryConstruct** [comment]
Can you attach a zip of the world file? Thanks!

**Comment by Ladeio** [comment]
I'm sure that I tried to open "The City Of Aliens" but I'm not sure about the rest.
[Worlds.zip](https://github.com/TEdit/Terraria-Map-Editor/files/5120274/Worlds.zip)

**Comment by TurtleSnake** [comment]
I'm currently facing the very same issue.
Attaching .wld files is not relevant because the same error shows up to **any** freshly created world, as none of them are neither corrupted or newer than the supported version.
![Screenshot_1](https://user-images.githubusercontent.com/52019105/92335070-cf65a980-f069-11ea-8362-313b0756e0f5.png)
What is currently boggling my mind is that the latest version of TEdit Max World value is 228, despite any newer world being 230. Is that supposed to work this way?

- OS: Windows 7 Ultimate 32-bit SP1
- TEdit Version: 4.0.0-beta32
- Terraria Version: 1.4.0.5

**Comment by moe41** [comment]
[Breach_of_Rich_Mahogany.zip](https://github.com/TEdit/Terraria-Map-Editor/files/5923256/Breach_of_Rich_Mahogany.zip)
i can't this world.
OS:windows10home64
TEdit Version:4.2.7.0
Terraria Version:1.4.1.2

**Comment by hazame4** [comment]
y i can load none of my world on 4.2.7 tedit too my spec is win7 professional 32bit and terraria 1.4.1.2

**Comment by xXmartin0311** [comment]
> y i can load none of my world on 4.2.7 tedit too my spec is win7 professional 32bit and terraria 1.4.1.2

Might not be the cause of your issue but it's been said that the program is not guaranteed to work with windows 7

**Comment by BinaryConstruct** [comment]
Additionally, 32 bit OS does not have enough memory for TEdit. It requires 2-6 gb depending on world size.
