### ISSUE TITLE
Option to make world "for the worthy"

### ISSUE THREAD

**Issue by DRKV333** [TEdit/Terraria-Map-Editor#1410]
**Is your feature request related to a problem? Please describe.**
I would like to toggle the effects of the `for the worthy` seed on a world using TEdit.

**Describe the solution you'd like**
Much like with drunk worlds, TEdit should also have a checkbox for setting the `getGoodWorld` field in a save.

**Describe alternatives you've considered**
I'm not sure if making a world both drunk and `for the worthy` would be a problem. Looking at how the game deals with these, I think it should be fine. It's not something that can happen naturally though. If it causes problem, this case should be disallowed.

**Comment by cokolele** [comment]
@BinaryConstruct This feature seems like a 5 minute fix.

Here you are already parsing a flag for it
https://github.com/TEdit/Terraria-Map-Editor/blob/84a6f91fc9535b50a686bfcbf494876b41bb5903/src/TEdit/Terraria/World.FileV2.cs#L515

You could just make same checkbox for it, just like for DrunkWorld
https://github.com/TEdit/Terraria-Map-Editor/blob/a1c0b2ccc5b05ed9ab2900df78fb38e386561003/src/TEdit/View/WorldPropertiesView.xaml#L395

I can't do C# so im just gonna leave this comment here instead of pull request

**Comment by BinaryConstruct** [comment]
Thanks, I will add for the next release.
