### ISSUE TITLE
TEdit reporting

### ISSUE THREAD

**Issue by XiEndST** [TEdit/Terraria-Map-Editor#1446]
![Screenshot_1](https://user-images.githubusercontent.com/73044503/97770787-8bfa5980-1b47-11eb-8a48-c27f1f66b683.png)

**Comment by BinaryConstruct** [comment]
This is a disclaimer indicating that you may disable error reporting if you wish. The file menu contains the option. Thank you.

Error reporting sends in crash data so that I can understand the issues users are seeing and be able to fix them faster, see this example:
![image](https://user-images.githubusercontent.com/456755/97771429-e1644580-1b0a-11eb-8be3-5ea6a36dde5b.png)  
![image](https://user-images.githubusercontent.com/456755/97771436-f9d46000-1b0a-11eb-8c56-cccc215868c1.png)
