### ISSUE TITLE
Multiplying chest/sign glitch

### ISSUE THREAD

**Issue by Lunasycthe** [TEdit/Terraria-Map-Editor#1545]
This maybe isnt as big a deal as game breaking bugs, but this has plagued me for years now on TEdit and I'd really like it to get sorted out... I feel like there's already been threads on it, but it's still happening so here goes. The chest's multiplied on the same spot and boosted the chest count to insane levels. I found 5 chests listed as being on one square. Usually this happens with chests I've accidentally cut part of the 4 square sprite out of, but it also happened with others like the desert chest. If I delete one the count doesnt go down. If I add one the count goes up by 3. Even worse when I remove all the chests (which I dont want to permanently do for obvious reasons) then the signs kick off with the same error, and I have no way of tracking those... Copying, deleting and repasting the entire world along with going through all the chests and deleting any half sprites I think fixed the chests, but now the signs are giving me the same error and I have no way of tracking those down... I've tried saving it in game hoping it'd just save one chest/sign in that area, but they still multiplied. The error says I wont be able to load the world in Terraria because there's too many chests/signs, but it loads and saves in game just fine. I dont know if it's a glitch in how TEdit calculates chests/signs, the chests/signs coding, or what, but I cant have the autosave on anymore, and I dont know if these extra layers of items might affect the game... So an option to find and delete any chest/sign less than 4 squares would be great, and something I can use to hunt down signs. I have too many to track down manually, but I'm sure I cant have 1700 and rising of them... This bug has been annoying me for years and now it's moved onto signs I cant seem to do anything about it...

**Comment by BinaryConstruct** [comment]
Can you please evaluate release 4.5.2 to see if it fixes your issue? https://github.com/TEdit/Terraria-Map-Editor/releases/tag/4.5.2

**Comment by Wamwod** [comment]
This is a bug just created a Plain world with zero chests and counter under Analysis tab added 3 instead of 1. The Analysis tab is reading the top left and two bottom tiles as their own chests instead of one.
![image](https://user-images.githubusercontent.com/71331178/135242818-7bed9a34-47a3-472c-b831-e8d482b1ea34.png)
No chests
![image](https://user-images.githubusercontent.com/71331178/135242922-0ba39f27-2952-4291-8d98-5d3b6615b787.png)
1 Chest
![image](https://user-images.githubusercontent.com/71331178/135243195-abacf8c6-02ca-41b7-8340-e3dc8410c4e1.png)
Bottom Left Tile missing
![image](https://user-images.githubusercontent.com/71331178/135243418-079f86e7-db47-415d-a319-a111cc65c0f8.png)
Top right Tile missing

TEdit V4.5.1 (Can't place sprites in 4.5.2 due to #1548 ) 
Windows 10.0.19042
