### ISSUE TITLE
Creative Power Time Speed Setting will not save 

### ISSUE THREAD

**Issue by Teto201** [TEdit/Terraria-Map-Editor#1795]
**Describe the bug**
The "Time Speed" Setting will not save after I click the "save" button above

**Steps to reproduce the behavior:**
1. Activate "Time Speed" setting and set it to any number. And activate anyone of the other settings in the "Creative Powers" Category. 
2. After that, click on save above and then on load. 
3. Now the "Time Speed" should be in that status before we edited, and any other settings should be in that status in that we changed it.

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/117540316/200138452-272cee2b-4cdc-40ec-8f1f-1797fa5552a8.png)
3.
![image](https://user-images.githubusercontent.com/117540316/200138800-8b8253f7-f11e-42eb-b4bf-68f176eff2b3.png)
4.
![image](https://user-images.githubusercontent.com/117540316/200138806-85958208-4fca-4571-af76-6149f1f49177.png)

 - OS: Windows 10 21H2
 - Version Tedit v4.11.5
 - Terraria Version v1.4.4.7

Sorry for my bad English

**Comment by defster** [comment]
Same issue. Once a create power has been set and saved, the tick is reset when you reload the world. There is no way to undo a change by deselecting it because its already marked as deselected. Selecting and deselecting it again has no effect.

In addition, the same thing happens to a few other tickboxes, for example to set the world as Crimson/Corrupted. Its hit or miss weather the choice can be reverted by unchecking the box.

**Comment by vilhelmen** [comment]
Confirming as well, was trying to see if I could disable biome spread in my Master save and time gets set to and stuck at 24x

**Comment by RussDev7** [comment]
Issue resolved in post #1874.
