### ISSUE TITLE
Autosave file storage spam.

### ISSUE THREAD

**Issue by Nifylau** [TEdit/Terraria-Map-Editor#1973]
After running WizTree to figure out what was eating my storage, I discovered that deep within my program files was 170GB of TEdit autosave files. 

For obvious reasons, this is not ideal and should not be happening.

![image](https://github.com/user-attachments/assets/8580420b-9afe-471b-861b-159ab9a1bfbd)

Win10 19045.5011, TEdit 4.16.0

**Comment by BinaryConstruct** [comment]
You can disable it from the file menu.

**Comment by VL4DST3R** [comment]
This should still be addressed in a proper way, i.e. keep only x amount of autosaves, not just disabling it outright.

Also this issue was already reported years ago here #1729 and the option is still enabled by default without any warning about it causing problems. I had my pc almost lock up on me because I had tedit open in the background and ended up with about 90gb of temp files without me realizing.
