### ISSUE TITLE
New Tool: Line Drawing

### ISSUE THREAD

**Issue by RlonRyan** [TEdit/Terraria-Map-Editor#325]
Draw Mode would work as follows:

[left_click] Free draw

[right_click] Line Draw

Line draw would work as follows:

User right clicks and sets point one.
User releases mouse and moves to a new point.
A line, not made of blocks, is drawn from point one to the mouse every time it moves for visualization.
User right clicks again, and set point two on the line, the line is generated now from point one to point two. The line thickness is set by changing the size parameter.

**Comment by kphillisjr** [comment]
I was doing some editing and noticed a couple of changes that will greatly improve the use of this tool.

- Line draw Preview - As it states, show a preview that is not yet applies to the map of the line that is generated. This is important since in larger maps a line someone makes can be several hundred tiles long. An example of this is to draw a wire from the top of the map to the lowest level of the map where you normally find obsidian items.

- Line Angle control - It'd be useful to control the line's angle. For example in paint.net when you draw a line, if you hold the Shift Key the lines being drawn are snapped to 15 degree intervals.
