### ISSUE TITLE
3.4 works perfectly, 3.5 does not

### ISSUE THREAD

**Issue by shuvok** [TEdit/Terraria-Map-Editor#597]
I had 3.4 tedit and always worked perfectly, recently I downloaded the 3.5 hoping for it to be even better, but it doesn't even work, the main screen where the map should be editable is fully black, basically the update is a failure... hopefully the last working version is still avaliable

**Comment by sweetloo32** [comment]
This has somewhat happened to me as well. I can't open or load a world. I can make a new one but if i click on the main screen area the entire thing turns black. I even tried making a new one and then saving it just to test that. To summarize it will not save at all as well as not being able to open a world and when you click on the area to actually edit it goes black.

**Comment by SBlogic** [comment]
I've been running 3.5.15047.30 with no such issues.  Please provide the contents of TEditLog.txt (in your Documents\My Games\Terraria folder).  Also, how much memory is installed in your computer?

**Comment by sweetloo32** [comment]
I mean its not much of a log per say because using TEdit doesn't crash. It just doesnt let me do anything except for create a new world, and close it. And once in a blue moon when I try it lets my place some stuff on this new created world but then i can't save.

06-26-2015 00:14: Starting TEdit 3.5.14228.27 
06-26-2015 00:14: OS: Microsoft Windows NT 6.1.7600.0 
06-26-2015 00:14: .Net >= 4.0 
06-26-2015 00:14: XNA 4.0 
06-26-2015 00:14: Terraria Data Path: S:\Program Files (x86)\Steam\steamapps\common\Terraria\Content 
06-26-2015 00:14: Creating Undo cache: C:\Users\lucian\AppData\Roaming\TEdit\undo_994997842 
06-26-2015 00:16: Removing undo cache: C:\Users\lucian\AppData\Roaming\TEdit\undo_994997842 
I have 16 gigabytes of Random Access Memory
