### ISSUE TITLE
Terraria Schematics Error

### ISSUE THREAD

**Issue by KandiHallowz** [TEdit/Terraria-Map-Editor#617]
Yesterday I spent the whole day making things and saving my old creations as terraria schematics so that I could make an awesome world. Today only half will load. The others say 'Index was outside the bounds of the arrays' I thought that by saving them I was ok to delete the worlds because I had so many. So I am hoping there is a way to fix this..

**Comment by IllyaMoskvin** [comment]
Just wanted to second this issue. I made some schematics on one computer, but when I transferred them to another, they would not load. I got the same out-of-bounds error. However, those same schematics did load successfully when I transferred them back to the original computer. I tried looking at the schematic files, but I'm not familiar with the way they are structured, so that went nowhere. If it will help, I can upload some of the schematics that are giving me trouble for reference.

**Comment by gogobebe2** [comment]
"Index was outside the bounds of the arrays" - You should give the rest of the error. I think that is an internal code error.
