### ISSUE TITLE
Exception Occured

### ISSUE THREAD

**Issue by jy130** [TEdit/Terraria-Map-Editor#682]
Application ran dozens of times today, then all the sudden an exception occurs? I have no idea how to read it but, it also seems to think Im running Windows NT, way off!?
![exception 9-13](https://cloud.githubusercontent.com/assets/14268394/9842041/9c04627e-5a65-11e5-9c22-90b8e0ca3512.jpg)

**Comment by SBlogic** [comment]
2000, XP, Vista, 7, 8, and 10 will report as NT because they're all NT-based operating systems.  6.1.7601 is Windows 7.

On the line that says "Root element is missing" is the complete name of a hidden config file.  Locate that file, rename it, then try running TEdit again.  It's possible something in that file got garbled.  Can you also provide the contents of the user.config file?

**Comment by BinaryConstruct** [comment]
Please try the latest beta versions.
