### ISSUE TITLE
ask for update and crush 'Unhandled Exception'

### ISSUE THREAD

**Issue by Nimblentfox** [TEdit/Terraria-Map-Editor#708]
I try most 3.6 build for Terraria 1.3.0.8 and I got an update, either yes or no will result in Unhandled Exception crush and provide me this log file.
https://www.dropbox.com/s/pbwuyiomui5mz7o/TEditLog.txt?dl=0

Before 1.3 update, I can use TEdit with Terraria 1.2.0.4 without any problem. I try with .NET 4.5.2 but no luck. Edit the TEditXna.exe.config CheckUpdates value to False, didn't make different.

Did I mass something up or it require more installation?

**Comment by enigmaquip** [comment]
See Error #672 
Specifically this comment by BinaryConstruct:

These issues are due to the change to Monogame from XNA. Since XNA is a discontinued product and not 64 bit compatible it needed to be replaced.

Monogame uses SharpDX for the core rendering, however it adds some new dependencies including having a DX11 compatible graphics card, Window7+ and functional drivers, whereas XNA would work even with out of date hardware.

**Comment by Nimblentfox** [comment]
Thank you very much, then I'll wait until update for Monogames. 
Manual build for another corruption barrier _oTL

**Comment by BinaryConstruct** [comment]
Please watch #751 for progress on this known issue.
