### ISSUE TITLE
Deco Sprites Missing

### ISSUE THREAD

**Issue by Zwod** [TEdit/Terraria-Map-Editor#809]
All cave deco sprites (165), are missing from the sprite selection, except for one.

**Comment by Darkstar0001** [comment]
It was the icicle from the ceiling. I figured that it would automatically change to the appropriate deco when placed, but it remained ice even when placed on stone, marble and granite. I even checked to see if it would look normal in-game, but it still looked like ice.

**Comment by Zwod** [comment]
Theres a temporary work around however, you can copy and paste them from elsewhere

**Comment by enigmaquip** [comment]
tile 165 is a weird beast that noone has ever wanted to touch, it's a multi-size sprite that contains both 1x2 and 1x1 sized stalagmites/stalactites. This only occurs in like 3 tiles so the sprite map loading from the xml and the sprite display in the sprite tab weren't ever coded to handle that. For now I've added in the 1x2 decos as they're first anyways, some is better than none I suppose. The code fix will be a project for the future

**Comment by Kojirremer** [comment]
Those tiles will change to the correct one when a tile is modified right next to them in-game (like hammering the block right next to it, or placing a torch sticking to the stalactite).
Not the prettiest workaround since it requires entering the game and fiddling with every single one, but it's the only one I know.
