### ISSUE TITLE
Chest contents wiped when copying

### ISSUE THREAD

**Issue by Seakuil** [TEdit/Terraria-Map-Editor#914]
## What were you doing when the issue occured?
Using select and copy to move chests from one area to another.

## Can you reproduce the issue?
Yes, select a chest and copy. Then paste to another area, the contents will be wiped when you look in it in game.

## What version of Terraria are you using?
1.3.3.3

**Comment by BinaryConstruct** [comment]
Have you checked to see if the wold contains over 1000 chests? This is a hard limit and Terraria cannot load more than that.

**Comment by Kojirremer** [comment]
Actually, his problem is probably the same as mine:
Chest content does get copied. However, in some cases it is pasted weirdly. Usually the chest content should exist on all four tiles of said chest, yes? Some times, however, when pasting a chest the content "shifts" to the right one tile. That makes the first two vertical tiles of the chest have nothing, whereas the other two will have the stuff, turning it into two chests.

Unfortunately I have no way to reproduce it, as it happens randomly and sometimes repasting the same chest in the same place fixes it.

**Comment by Seakuil** [comment]
There's no way near 1000 chests. Kojirremer's problem also happens to me. This is what happens:
1. You copy a chest containing stuff, with a existing name and chest type. 
2. You paste the chest, the name and type of it is blank but the contents appear to be there.
3. Go ingame and the contents are gone.
4. Go in tedit again and the contents are gone. 
5. Try copying the chest again, but this time change the copied blank type field to what the chest is and it does the shift to the right thing and creates half a chest next to it.

The half a chest is empty, the complete chest has the items in. So in some ways this a work-around, but you then need to go ingame and remove the half-chests.

![chestglitch](https://cloud.githubusercontent.com/assets/23421481/20425393/48b67380-ad72-11e6-93a1-8eba6394bbe4.PNG)

**Comment by kyd462** [comment]
I have had the same issue, and it does seem to be reproduced randomly. I have noticed there's a much greater chance of it happening when copy/pasting multiple chests.

This never used to be an issue. It has only appeared since at least BETA_v3.9.16332.165 ... To my knowledge, I was copying chests prior to that without issue.

**Comment by enigmaquip** [comment]
Try 3.9.16342.175 and let me know if this still occurs

**Comment by Darkstar0001** [comment]
I'm using version 3.9.16350.618, and I'm also having this problem. My chests, and signs, for that matter, never copy correctly. Not only are the contents lost, but I can't even view the contents in TEdit, unless I place another sprite over it.

I guess pasting the same sprite over it would delete the contents, but I can't access them in TEdit anyway, and the chests are empty and the signs are blank when viewed in-game.

**Comment by Kojirremer** [comment]
https://github.com/TEdit/Terraria-Map-Editor/issues/887 Refer to this, I sort of found the problem.
In order to copy chest or sign schemas without issue, make sure to delete any previous chests/signs in the target position, then SAVE (the tile changes need to be validated, and that only happens during saving), THEN paste your stuff, and save again so they get validated.
Cumbersone, but works.

**Comment by BinaryConstruct** [comment]
#1028 created to track this issue
