### ISSUE TITLE
Unhandled Exception (v 3.9)

### ISSUE THREAD

**Issue by JesusADJ** [TEdit/Terraria-Map-Editor#943]
Hi, I've been receveing this error message when I try to iniciate the .exe file.
"An unhandled exception has occured. Please copy the log from: (...) to the GitHub Issues list. The program will now exit"
Here is the log:
[TEditLog.txt](https://github.com/TEdit/Terraria-Map-Editor/files/660092/TEditLog.txt)
Is this a common error? Does someone knows how to fix it?
Thanks

**Comment by BinaryConstruct** [comment]
You might try some of the suggestions in #751. 

Otherwise the error message is indicating some issue initializing directx on your GPU. 

12-19-2016 02:41:23: Error - HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: The specified device interface or feature level is not supported on this system.

**Comment by JesusADJ** [comment]
I use an amd card, going to try the reinstallation of directx

**Comment by BinaryConstruct** [comment]
Did you have any success?

**Comment by JesusADJ** [comment]
Got it "fixed" by doing the same thing I've got to do for launching GTA V, got to disable my graphics Card every time want to play it or start TEdit, the bad thing is that I've got to do it every time I want to use it, and it becomes very lag, since I can't use my graphics card, it works by now, thanks.
