### ISSUE TITLE
Not an error, but 2 questions...

### ISSUE THREAD

**Issue by Poot5** [TEdit/Terraria-Map-Editor#995]
I know it's not that great to upload questions on an Issue board, but I need 2 answers.
1. Is there a way to change the number of Angler Quests completed?
2. How does Find Chest with <certain item> work exactly?
There are no errors, but I only need to know those 2... Sorry.

**Comment by uselessscat** [comment]
@Poot5 I think the "Find Chest with" works like this:

1. The dialog ask the name of the item. Write the name of the object, for example: "Bomb"
2. A list of chests coordinates containing that item will appear
3. Double click on the coordinate so that the map viewer scrolls
4. Right click on the chest to see its contents in the side panel

That is all
